# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: instance-vol-1-1
    vol_size: 20
  - vol_name: instance-vol-1-2
    vol_size: 20
  - vol_name: instance-vol-2-1
    vol_size: 20
  - vol_name: instance-vol-2-2
    vol_size: 20
  - vol_name: instance-vol-3-1
    vol_size: 20
  - vol_name: instance-vol-3-2
    vol_size: 20
  - vol_name: instance-vol-4-1
    vol_size: 20
  - vol_name: instance-vol-4-2
    vol_size: 20

# Security group
security_groups:
  - name: ssh
    description: " security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0


  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

  
  
# Instance
instances:
  - name: instance-1
    volumes: ['instance-vol-1-1', 'instance-vol-1-2']
  - name: instance-2
    volumes: ['instance-vol-2-1', 'instance-vol-2-2']
  - name: instance-3
    volumes: ['instance-vol-3-1', 'instance-vol-3-2']
  - name: instance-4
    volumes: ['instance-vol-4-1', 'instance-vol-4-2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: test_jiajun
instance_flavor: uom.mse.1c4g
