
---
- name: Creating a new directory
  become: yes
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory


- name: create proxy file for docker
  become: yes
  file:
    path: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    state: touch


- name: Add proxy for docker
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    block: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"

- name: to access the docker.sock, have to change the permission
  become: yes
  file: 
    path: /var/run/docker.sock
    mode: 0777


- name: reload the docker daemon
  command: systemctl daemon-reload
  become: yes

- name: restart the docker
  command: systemctl restart docker
  become: yes
