---
# - hosts: localhost
  
#   vars_files:
#     - host_vars/instance.yaml
#   gather_facts: true

#   roles:
#     - role: add-privateKey

- hosts: instances
  vars_files:
    - host_vars/instance.yaml
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
      # - role: openstack-enviroment
      # - role: install-docker
      #  - role: install-package
      # - role: docker-enviroment
      

- hosts: cluster
  vars_files:
    - host_vars/instance.yaml
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
    - role: couchDB_setup